### PR TITLE
[WIP]カスタマイズ電卓画面の実装

### PR DESCRIPTION
**Pull request by rni-hong**

### CODE REVIEW

**Comment by rni-hong** [comment]
miss with place

**Comment by rni-hong** [comment]
sorry the merge brach was wrong 🙏

**Comment by DevLiuSir** [comment]
I have time to have a look in the evening. Thank you for your pr.

**Comment by DevLiuSir** [comment]
> sorry the merge brach was wrong 🙏

You don't understand how to use pr, I can't merge your pr.

**Pull request closed without merging**
